<?php

/**
 * Functionality at the database level
 */

namespace PHPCouchDB;

/**
 * Working with a particular database is all done here.  Usually instantiated
 * by the Server object as it has the connection details we need to use.
 */


class Database
{
    protected $client;
    protected $db_name;


    /**
     * Constructor for the Database object - this is usually called by
     * Server::useDb rather than directly
     *
     * @param \GuzzleHTTP\ClientInterface $client Our HTTP client
     * @param string $db_name The datbase to connect to
     */

    public function __construct(\GuzzleHttp\ClientInterface $client, string $db_name)
    {
        $this->client = $client;
        $this->db_name = $db_name;
    }

    /**
     * Get the name of the database
     */
    public function getName() : string
    {
        return $this->db_name;
    }

    /**
     * If you need to make a request that isn't supported by this library,
     * use this method to get the client to use.  Aimed at more advanced
     * users/requirements
     */
    public function getClient() : \GuzzleHttp\ClientInterface
    {
        return $this->client;
    }

    /**
     * Format object for var_dump(), removing large properties
     */
    public function __debugInfo()
    {
        $result = get_object_vars($this);
        unset($result['client']);
        return $result;
    }

    /**
     * Fetch all the documents from the database
     *
     * @param array $options  Any modifiers needed for the query  These include:
     *      - include_docs   Defaults to true
     * @return array The array contains `PHPCouchDB\Document` objects
     */
    public function getAllDocs($options = []) : array
    {
        $endpoint = "/" . $this->db_name . "/_all_docs";
        $query = ["include_docs" => "true"];
        $response = $this->client->request("GET", $endpoint, ["query" => $query]);
        if ($response->getStatusCode() == 200) {
            // try to decode JSON
            if ($json_data = json_decode($response->getBody(), true)) {
                // we have some data - extract the docs to return
                $docs = [];
                foreach ($json_data["rows"] as $document) {
                    $docs[] = new Document($this, $document["doc"]);
                }
                return $docs;
            } else {
                throw new Exception\ServerException('JSON response not received or not understood');
            }
        }
    }

    /**
     * Create a new document in the database
     *
     * @param array $doc  An array representing the document's keys and values.
     *  The data can be nested arrays, lists, anything
     *  - if you include an "id" key, this will become the document ID,
     *      otherwise it'll be autogenerated
     * @return PHPCouchDB\Document a document object of your new doc
     */
    public function create($doc)
    {
        if (!is_array($doc)) {
            throw new Exception\DatabaseException('A document is required, in array format');
        }

        // do we have the ID?
        if (isset($doc['id']) && !empty($doc['id'])) {
            // remove the ID from the array, then use it in the URL with PUT
            $id = $doc['id'];
            unset($doc['id']);
            $endpoint = "/" . $this->db_name . "/" . $id;
            $verb = 'PUT';
        } else {
            // no ID, make a POST request to create the record
            $endpoint = "/" . $this->db_name . "/";
            $verb = 'POST';
        }

        try {
            $response = $this->client->request($verb, $endpoint, ['json' => $doc]);
            if ($response->getStatusCode() == 201 && $response_data = json_decode($response->getBody(), true)) {
                $id = $response_data['id'];
                // all good.  Let's fetch the doc and return it
                $fetched_data = json_decode($this->client->get('/' . $this->db_name . '/' . $id)->getBody(), true);
                return new Document($this, $fetched_data);
            }
        } catch (\GuzzleHttp\Exception\ConnectException $e) {
            throw new Exception\ServerException(
                "Could not create record.  Error: " . $e->getMessage(),
                0,
                $e
            );
        }
    }

    /**
     * Get a document whose ID you know
     *
     * @param string $id The doc's unique identifier
     * @return PHPCouchDB\Document The doc with the specified ID
     * @throws PHPCouchDB\Exception\ServerException if the response can't be understood
     * @throws PHPCouchDB\Exception\DatabaseException if the doc isn't found
     */
    public function getDocById($id) : Document
    {
        $endpoint = "/" . $this->db_name . "/" . $id;
        try {
            $response = $this->client->request("GET", $endpoint);
            if ($data = json_decode($response->getBody(), true)) {
                $doc = new Document($this, $data);
                return $doc;
            } else {
                throw new Exception\ServerException('JSON response not received or not understood');
            }
        } catch (\GuzzleHttp\Exception\ClientException $e) {
            $status = $e->getResponse()->getStatusCode();
            if ($status == 404) {
                // not really a disaster, the doc just isn't there so throw specific exception
                throw new Exception\DocumentNotFoundException('Document not found');
            } else {
                throw new Exception\DatabaseException('The document could not be retrieved', 0, $e);
            }
        }
    }
}
